-- user_records — 보컬 MBTI · 점수 · AI 코칭 (analysis_records 보조/대체)
-- Supabase SQL Editor → New Query → Run

create table if not exists public.user_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  vocal_mbti text,
  score_json jsonb,
  coaching_text text,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_records_user_created
  on public.user_records (user_id, created_at desc);

alter table public.user_records enable row level security;

drop policy if exists "Allow service insert user_records" on public.user_records;
drop policy if exists "Allow service select user_records" on public.user_records;

-- 베타: anon key + 앱 자체 user_id (kakao_*, demo_*). 정식 Auth 연동 시 강화.
create policy "Allow service insert user_records"
  on public.user_records for insert
  with check (true);

create policy "Allow service select user_records"
  on public.user_records for select
  using (true);
